# Generated by Django 5.0.2 on 2024-02-29 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solutions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_space', models.CharField(max_length=50)),
                ('search_method', models.CharField(max_length=70)),
                ('num_iterations', models.IntegerField()),
                ('task', models.CharField(max_length=70)),
                ('solution', models.CharField(max_length=900)),
                ('best_reward', models.FloatField()),
                ('current_iteration', models.IntegerField(default=0)),
                ('uuid', models.CharField(default='', max_length=150, null=True)),
            ],
        ),
    ]
