# Generated by Django 5.0.2 on 2024-03-05 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutions',
            name='crashable',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='solutions',
            name='leaps_behaviour',
            field=models.BooleanField(null=True),
        ),
    ]
