# Generated by Django 5.0.2 on 2024-03-05 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_solutions_crashable_solutions_leaps_behaviour'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutions',
            name='seed',
            field=models.IntegerField(null=True),
        ),
    ]
