# Generated by Django 5.0.2 on 2024-03-07 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_solutions_seed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solutions_Leaps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_space', models.CharField(max_length=50)),
                ('search_method', models.CharField(max_length=70)),
                ('num_iterations', models.IntegerField()),
                ('task', models.CharField(max_length=70)),
                ('solution', models.CharField(max_length=900)),
                ('best_reward', models.FloatField()),
                ('current_iteration', models.IntegerField(default=0)),
            ],
        ),
    ]
