# Generated by Django 5.0.2 on 2024-03-07 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_solutions_leaps'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutions_leaps',
            name='id_task',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
