# Generated by Django 5.0.2 on 2024-03-07 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_solutions_leaps_id_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutions_leaps',
            name='state_task',
            field=models.CharField(max_length=900, null=True),
        ),
    ]
