# Generated by Django 5.0.2 on 2024-03-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_solutions_leaps_state_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutions_leaps',
            name='state_task',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
