# Generated by Django 5.0.2 on 2024-03-07 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_alter_solutions_leaps_state_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutions_leaps',
            name='seed',
            field=models.IntegerField(null=True),
        ),
    ]
