# Generated by Django 5.0.2 on 2024-03-13 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_solutions_leaps_seed'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutions_leaps',
            name='reward_CleanHouse',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='solutions_leaps',
            name='reward_DoorKey',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='solutions_leaps',
            name='reward_FourCorners',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='solutions_leaps',
            name='reward_Harvester',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='solutions_leaps',
            name='reward_Maze',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='solutions_leaps',
            name='reward_OneStroke',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='solutions_leaps',
            name='reward_Seeder',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='solutions_leaps',
            name='reward_Snake',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='solutions_leaps',
            name='reward_StairClimber',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='solutions_leaps',
            name='reward_TopOff',
            field=models.FloatField(null=True),
        ),
    ]
